services:
  - type: web
    name: fake-news-app
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: FACT_CHECK_API_KEY
        sync: false
